### ISSUE TITLE
Missing Things

### ISSUE THREAD

**Issue by aiantics** [Naofel-eal/Fortnite_aimbot#1]
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\naofe\\Documents\\Personnel\\Informatique\\FortniteIA\\yolov7\\workspace\\weights\\weightsV3.pt'

**Comment by Naofel-eal** [comment]
I haven't publish the weights of the neural networks to avoid that my program being used for malicious purposes.

**Comment by aiantics** [comment]
so this is not to be used? just to be looked at and learn from?

**Comment by Naofel-eal** [comment]
Exactly, I don't want any form of cheat in games.

**Comment by aiantics** [comment]
alright, thanks for the reply. I completely understand & support your decision.
